config/routes.rb
Rails.application.routes.draw do

  
  namespace :admin do
    root :to => redirect('/admin/configs')

    resources :users
    resources :configs
   
  end

  
  root               'static_pages#home'
  get   'login'   => 'sessions#new'
  get   'help'    => 'static_pages#help'
  get   "configure"  => "configs#new", :as => "configure"
  post  "configure"  => "configs#create"
  get   "configlist" => "configs#index"
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  post  'login'   => 'sessions#create'
  delete'logout'  => 'sessions#destroy'
  get   'rack1'   => 'static_pages#rack1'
  get   'rack2'   => 'static_pages#rack2'
  get   'rack3'   => 'static_pages#rack3'
  get   'rack4'   => 'static_pages#rack4'
  get   'rack5'   => 'static_pages#rack5'
  get   'rack6'   => 'static_pages#rack6'

  resources :configs, only: [:new, :create, :show]
  resources :users, only: [:edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get "*path" => redirect("/") #redirect invalid url

end

 

app/models/config.rb
class Config < ActiveRecord::Base
	belongs_to :user, class_name: "Config", foreign_key: :user_id
	validates :project, :rack_q, presence: true
	validates :rack_q, :numericality => {:only_integer => true, :less_than_or_equal_to => 6, :greater_than => 0}

    extend FriendlyId
    friendly_id :number, slug_column: :number, use: [:slugged,:finders]
    include NumberGenerator.new(prefix: 'C')

    def proposal_link
    	if self.rack_q == 1
    		"rack1"
    	elsif self.rack_q == 2
    		"rack2"
    	elsif self.rack_q == 3
    		"rack3"
    	elsif self.rack_q == 4
    		"rack4"
    	elsif self.rack_q == 5
    		"rack5"
    	elsif self.rack_q == 6
    		"rack6"	
    	end
    end

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << column_names
            all.each do |config|
                csv << config.attributes.values_at(*column_names)
            end
        end
    end
end

app/controllers/admin/configs_controller.rb
class Admin::ConfigsController < Admin::BaseController
  
  def index
    @search = Config.search(params[:q])
    @configs = @search.result.paginate(:page => params[:page], :per_page => 50).order('updated_at DESC')
 	respond_to do |format|
 		format.html
 		format.csv { send_data @configs.to_csv}
 		format.xls { send_data @configs.to_csv(col_sep: "\t")}

 	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  	   flash[:success] = "Profile updated"
	   redirect_to :back
  	else
  	   flash[:danger] = "Name can't be empty. / Contact Number only accept number characters." 
  	   redirect_to :back
  	end
  end

  	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_url
	end
  
private

 	 def user_params
		params.require(:user).permit(:name, :email, :contact_number, :company, :password, :password_confirmation)
 	 end

	# Before filters 
	# Confirms a logged-in user.
	def logged_in_user #used above, for before_action
		unless logged_in?
			store_location
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end


	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end

end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController

	before_action :correct_user_config, only: [:show]

	def new
		@config = Config.new
	end

	def create
		@config = current_user.configs.build(config_params)
		  if @config.save
			redirect_to config_path(@config)
		  else
		  	render 'new'
	  	end
	end

	def show
		@config = Config.find(params[:id])
	end

	def index
		@search = current_user.configs.search(params[:q])
    	@configs = @search.result.paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
	end

private

 	 def config_params
		params.require(:config).permit(:project, :rack_q, :comment)
 	 end

	# Confirms the correct user.
	def correct_user_config
		@user = current_user.id
		@config = Config.find(params[:id])
		redirect_to(root_url) unless @user == @config.user_id
	end


end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/configs/index.html.erb
<div class="container" style="padding-top: 30px; padding-bottom: 100px;">

  <div class="identity">
    <p> Hi, <%= current_user.name %> </p>
    <%= current_user.company %><br>
    <%= current_user.email %>
    <% if current_user.status == "Gold NSP" %>
      <p> You have Gold Access!  <span style="color: blue;">Perks: (5% discount)</span></p>
    <% elsif current_user.status == "Silver NSP" %>
      <p> You have Silver Access!  <span style="color: blue;">Perks: (7% discount)</span></p>
    <% elsif current_user.status == "Platinum NSP" %>
      <p> You have Platinum Access!  <span style="color: blue;">Perks: (10% discount)</span></p>
    <% else current_user.status = "none" %>
    <% end %>
</div>


<table class="table order_table" style="font-size: 15px;">
  <thead class="thead-inverse">
    <tr>
      <th style="width: 10%; text-decoration: underline;"><%= sort_link @search, :created_at, "Date Created" %></th>
      <th style="width:35%;">Project</th>
      <th style="width:15%;">Rack Quantity</th>
      <th style="width:35%;">Proposal Link</th>
    </tr>
  </thead>

  <tbody>

    <% @configs.each do |config| %>
      <tr>
        <td><%= config.created_at.strftime('%a, %d %b %Y %H:%M:%S') %></td>
        <td><%= config.project %></td>
        <td><%= config.rack_q %></td>
        <td><%= link_to config.number, config_path(config), style: "color: #ff8c00; text-decoration: underline; " %></td>
        <td></td>
      </tr>
     <% end %>
  </tbody>
</table>
<br>

</div>

app/views/configs/new.html.erb
<% provide(:title, 'Configure') %>

	
	<div class="config container">
		<div class="col-lg-6 col-lg-offset-3">

				<p class="loginvertiv">VERTIV</p>
				<p class="loginsmartrow">SMARTROW+ <br>Proposal<br>Configurator</p>
				<br>
				<br>
			
			<%= render "shared/error_messages", :target => @config %>

				<%= form_for @config, url: configure_path do |f| %> 
					<%= f.label :project, "Project Name" %>
					<br>
					<span class="configdesc">*Please indicate project location to accomodate delivery and installation cost (example: Jabatan ABC, KL)</span>
					<br>
					<%= f.text_field :project, class: 'form-control' %>


					<%= f.label :rack_q, "Rack Quantity" %>
					<br>
					<span class="configdesc">*Number of usable racks needed by end-user</span>
					<br>
					<%= select_tag "config[rack_q]", options_for_select([ "1", "2", "3", "4", "5", "6" ], "1"), class: 'form-control' %>
					<br>
					<br>
					<%= f.label :comment, "Comment (Optional)" %>
					<br>
					<span class="configdesc">*Additional information such as:
					<br>
					600mm or 800mm racks needed in the Smartrow+.
					<br>
					Piping length in feet or meters
					<br>
					Other additional requirements (KVM/IT) </span>
					<br>
					<%= f.text_area :comment, class: 'form-control' %>


					<%= f.submit "Create my proposal", class: "ghost-button-transition-config" %>
				<% end %>
			</div>
	</div>

app/views/configs/show.html.erb
<div class="user_config">

<div class="container config_details">


<h1> <span style="font-size: 0.5em; color: #566573; font-weight: bold;"> Proposal Number </span>  <br> <%= @config.number %> </h1> 
<h1> <span style="font-size: 0.5em; color: #566573; font-weight: bold;"> Project Name </span> <br> <%= @config.project %> </h1> 

</div>
	
	<%if @config.rack_q == 1 %>
		<%= render "static_pages/rack1" %>
	<% elsif @config.rack_q == 2 %>
		<%= render "static_pages/rack2" %>
	<% elsif @config.rack_q == 3 %>
		<%= render "static_pages/rack3" %>
	<% elsif @config.rack_q == 4 %>
		<%= render "static_pages/rack4" %>	
	<% elsif @config.rack_q == 5 %>
		<%= render "static_pages/rack5" %>
	<% elsif @config.rack_q == 6 %>
		<%= render "static_pages/rack6" %>
	<% end %>


</div>		