config/routes.rb
Rails.application.routes.draw do

  
  namespace :admin do
    root :to => redirect('/admin/configs')

    resources :users
    resources :configs
   
  end

  
  root               'static_pages#home'
  get   'login'   => 'sessions#new'
  get   'help'    => 'static_pages#help'
  get   "configure"  => "configs#new", :as => "configure"
  post  "configure"  => "configs#create"
  get   "configlist" => "configs#index"
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  post  'login'   => 'sessions#create'
  delete'logout'  => 'sessions#destroy'
  get   'rack1'   => 'static_pages#rack1'
  get   'rack2'   => 'static_pages#rack2'
  get   'rack3'   => 'static_pages#rack3'
  get   'rack4'   => 'static_pages#rack4'
  get   'rack5'   => 'static_pages#rack5'
  get   'rack6'   => 'static_pages#rack6'

  resources :configs, only: [:new, :create, :show]
  resources :users, only: [:edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get "*path" => redirect("/") #redirect invalid url

end

 

app/views/layouts/admin/_header.html.erb
<div class="admin-nav">

	<div class="admin-nav-button">
			<span class="menu-toggle"><i class="fa fa-bars"></i></span>
	</div>

	<div class="admin-nav-title">
		<%= link_to "Administration Site", admin_configs_path %>
	</div>

	<div class="admin-user" style="float: right; margin-right:45px;">
		<span style="margin-right: 10px;"> Hi, <%=current_user.name %>! </span>
		<span> <%= link_to "Go To Configurator", configure_url, class: "btn btn-success", style: "margin-bottom: 5px;" %></span>
	</div>



</div>

<div id="wrapper">
<nav class="navbar sidebar" role="navigation">
	<div id="sidebar-wrapper">
		<ul class="sidebar-nav nav-stacked">
			<li><%= link_to "Configuration List", admin_configs_path %></li>
			<li><%= link_to "User List", admin_users_path %></li>
			<li><%= link_to "New User", new_admin_user_path %></li>
		</ul>
	</div>
</nav>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html lang="en">

	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>

<body>
    
	<%= render 'layouts/admin/header' %>

    <div id="page-content-wrapper">

		    	<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>" id="flash"><%= message %></div>
				<% end %>
		        <%= yield %>

	</div>
	</div>

</body>

</html>