config/routes.rb
Rails.application.routes.draw do

  
  namespace :admin do
    root :to => redirect('/admin/configs')

    resources :users
    resources :configs
   
  end

  
  root               'static_pages#home'
  get   'login'   => 'sessions#new'
  get   'help'    => 'static_pages#help'
  get   "configure"  => "configs#new", :as => "configure"
  post  "configure"  => "configs#create"
  get   "configlist" => "configs#index"
  get   "signup"  => "users#new", :as => "signup"
  post  "signup"  => "users#create"
  post  'login'   => 'sessions#create'
  delete'logout'  => 'sessions#destroy'
  get   'rack1'   => 'static_pages#rack1'
  get   'rack2'   => 'static_pages#rack2'
  get   'rack3'   => 'static_pages#rack3'
  get   'rack4'   => 'static_pages#rack4'
  get   'rack5'   => 'static_pages#rack5'
  get   'rack6'   => 'static_pages#rack6'

  resources :configs, only: [:new, :create, :show]
  resources :users, only: [:edit, :update]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get "*path" => redirect("/") #redirect invalid url

end

 

app/views/layouts/_footer.html.erb
<div class="footer" id="footer">
	<div class="footer_left">
		<span>Vertiv Smartrow+ 2018</span>
	</div>

</div>

app/views/layouts/_header.html.erb
    <header class="header">
      <a href="#" class="header_icon"></a>
			<%= link_to image_tag("logo1.png", alt: "ver"), root_path, id: "logo1"%><%= link_to "Vertiv Smartrow+", root_path, id: "logo" %>



      	<nav class="menu">

			<%= link_to "Overview", root_path, class: "underline" %>
			<%= link_to "Configure", configure_url, class: "underline"  %>
			<%= link_to "Contact Us", help_path, class: "underline"  %>
			<%= link_to "Brochure", "https://www.vertivco.com/globalassets/products/facilities-enclosures-and-racks/integrated-solutions/smartrow-plus-brochure.pdf", class: "underline"  %>
			
			
			<div class = "right-side">
			<% if logged_in? %>
				<div class="dropdown">
					<a href="#" class="dropbtn disable_link">Welcome, <%= current_user.name %>! &nbsp; <span class="caret"></span></a>
					<div class="dropdown-content">
						<%= link_to "My Config", configlist_url, class: "disable_link" %>
						<%= link_to "Reset PW", edit_user_path(id: current_user.id), class: "disable_link" %>
						<%= link_to "Log out", logout_path, method: "delete", class: "disable_link" %>

					</div>
				</div>
			<% else %>
				<%= link_to "Log in", login_path, class: "login_h_button" %>
			<% end %>
			</div>	
		</nav>


	</header>


	<div class="not_home_site">

app/views/layouts/_home_header.html.erb
    <header class="head home_header">
      <a href="#" class="header_icon"></a>
			<%= link_to image_tag("logo1.png", alt: "tea the everything apparel tee"), root_path, id: "logo1"%>
			<%= link_to "Vertiv Smartrow+", root_path, id: "logo" %>

 

      	<nav class="menu">

			<%= link_to "Overview", root_path, class: "underline" %>
			<%= link_to "Configure", configure_url, class: "underline"  %>
			<%= link_to "Contact Us", help_path, class: "underline"  %>
			<%= link_to "Brochure", "https://www.vertivco.com/globalassets/products/facilities-enclosures-and-racks/integrated-solutions/smartrow-plus-brochure.pdf", class: "underline"  %>
			
			
			<div class = "right-side">
			<% if logged_in? %>
				<div class="dropdown">
					<a href="#" class="dropbtn disable_link">Welcome, <%= current_user.name %>! &nbsp; <span class="caret"></span></a>
					<div class="dropdown-content">
						<%= link_to "My Config", configlist_url, class: "disable_link" %>
						<%= link_to "Reset PW", edit_user_path(id: current_user.id), class: "disable_link" %>
						<%= link_to "Log out", logout_path, method: "delete", class: "disable_link" %>
					</div>
				</div>
			<% else %>
				<%= link_to "Log in", login_path, class: "ghost-button-transition login_button" %>
			<% end %>
			</div>	
		</nav>


	</header>


	<div class="home_site">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title><%= full_title(yield(:title)) %></title>
				<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
				<meta name="turbolinks-cache-control" content="no-cache">
				<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
				<%= csrf_meta_tags %>
				<%= render 'layouts/shim' %>
		</head>

		<div class="site-container">
 			<div class="site-pusher">

				<body>
				    <% if current_page?(root_path) %>
	    				<%= render 'layouts/home_header' %>
					<% else %>
			    		<%= render 'layouts/header' %>
					<% end %>

	    			<div class="site-content">
	      				<div class="flash_message">
							<%= render 'shared/flash' %>
						</div>
							<%= yield %>	
							<%= render 'layouts/footer' %>
					</div> <!-- END site-content -->
		    		
		    		<div class="site-cache" id="site-cache"></div>
		 			
		 			</div> <!-- END header-->
				</body>
			</div><!-- END site-pusher -->

		</div> <!-- END site-container -->				
	</html>